name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build Node.js Docker Image and Deploy to Minikube
    steps:
    - uses: actions/checkout@v2

    - name: Start Minikube
      uses: medyagh/setup-minikube@master

    - name: Verify Minikube Status
      run: |
        minikube version
        kubectl config view
        kubectl get nodes

    - name: Build Docker Image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ./Dockerfile -t devopshint/node-app:latest .
        docker images

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s-node-app.yaml

    - name: Check pod status
      run: kubectl get pods

    - name: Describe nodejs service
      run: kubectl describe svc nodejs-app

    - name: Wait for Minikube to be ready
      run: |
        echo "Waiting for Minikube to start..."
        sleep 30  # Wait for 30 seconds

    - name: Test service URLs
      run: |
        minikube service list
        minikube service nodejs-app --url

